# Generated by Django 5.2.16 on 2026-07-12 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('RC', 'Registration Certificate'), ('INSURANCE', 'Insurance'), ('PERMIT', 'Permit'), ('FITNESS', 'Fitness Certificate'), ('PUC', 'Pollution Certificate'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(upload_to='vehicle_docs/')),
                ('expiry', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle')),
            ],
        ),
    ]
